name: CI/CD Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 2375:2375
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock


  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Use the version appropriate for your project

    - name: Restore dependencies
      run: dotnet restore ./Code/SigmaCandidateTask/SigmaCandidateTask.API.csproj

    - name: Build
      run: dotnet build ./Code/SigmaCandidateTask/SigmaCandidateTask.API.csproj --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ./Code/SigmaCandidateTask/SigmaCandidateTask.API.csproj --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish ./Code/SigmaCandidateTask/SigmaCandidateTask.API.csproj --no-restore --configuration Release --output ./publish

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: faroukmk/sigmatask:latest
